apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
    service: catalog-service
    version: catalog
spec:
  type: ClusterIP
  selector:
    app: catalog-service
    service: catalog-service
    version: catalog
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 9001
